# Generated by Django 4.2.5 on 2023-10-18 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('man', models.PositiveIntegerField()),
                ('kids', models.PositiveIntegerField()),
                ('animals', models.BooleanField()),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания заказа')),
                ('is_active', models.BooleanField(default=False, help_text='Флаг активности заказа')),
                ('activation_code', models.CharField(blank=True, help_text='Код активации заказа', max_length=40)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='apartment.apartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
