# Generated by Django 4.2.5 on 2023-10-18 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SendProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Сообщения об проблеме')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_problems', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Вопрос пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Жалоба пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
