# Generated by Django 4.2.5 on 2024-07-11 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='price_dollar',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
