# Generated by Django 4.2.5 on 2024-07-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_remove_apartment_price_dollar_delete_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фотография'),
        ),
    ]
